# Generated by Django 4.2.9 on 2024-01-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('light_intensity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('test_field', models.CharField(default='test', max_length=100)),
            ],
        ),
    ]
