# Generated by Django 4.2.9 on 2024-06-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='light_intensity',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='test_field',
        ),
    ]
